(function(root) {
  'use strict';
  const bundle=typeof module==='object' && module.exports?require('./access-materials.js'):root.TracewrightAccessMaterials;
  const {tickets,sources,steps,transitions,intake_seed}=JSON.parse(JSON.stringify(bundle));
  const lanes=['Input meaning and identity','Approval, correction and activation','Model evaluation and variables','Authority, operations and learning'];
  const R=(source_id,section_id)=>({source_id,section_id});
  function E(id,title,state,lane,refs,marks,observation,reasons,alternatives,action_ids,step_ids,ticket_ids) {
    const excerpt=refs.map(r=>sources.find(s=>s.id===r.source_id).sections.find(s=>s.id===r.section_id).text).join('\n\n');
    return {id,title,finding_state:state,lane,source_refs:refs,source_ids:[...new Set(refs.map(r=>r.source_id))],excerpt,excerpt_kind:'Compared excerpts from fictional materials',marked_text:marks.map(([text,reason])=>({text,label:'Inspect here',reason})),observation,reasoning_chain:reasons,alternative_explanations:alternatives,action_ids,step_ids,ticket_ids,texture_axis:'not_applicable',attention:({observed_gap:'Documented mismatch',concern:'Control concern',unknown:'Not established',observed_control:'Observed in this sample'})[state]};
  }
  const evidence=[
    E('PA-E01','A negated permission becomes an active write grant','observed_gap',lanes[0],[R('PA-S04','P002'),R('PA-S05','P002')],[['No write access to production is requested','The request explicitly excludes write access. Compare meaning, not the requestor\'s character.'],['write_access=true','The extraction reverses the permission and the logged activation carries it forward.']],'P002 excludes writes, but the extracted field and activated grant include them.',['Align the original phrase, extracted polarity and grant event.','An approver name or fluent notice does not repair the meaning change.'],['A separately authorised change could justify wider scope, but this trace supplies no such request or authority.'],['PA-A01','PA-A06'],['PA-EXTRACT','PA-ASSESS','PA-GRANT'],['P002']),
    E('PA-E02','Parser completion is mistaken for complete scope','observed_gap',lanes[0],[R('PA-S02','unknown'),R('PA-S03','inputs'),R('PA-S04','P003')],[['completeness=complete even when unresolved_scope=true','A technical success label overstates what was read.'],['pages_received=3; pages_parsed=2','The unread third page remains outside the evidence.']],'The configuration marks incomplete extraction complete, despite the procedure requiring unknown content to remain unknown.',['Separate processing status from the content\'s completeness.','A hold route does not fix a contradictory completeness field used elsewhere.'],['The hold may prevent activation in this path. The missing page does not establish either inappropriate access or a safe request.'],['PA-A01','PA-A03'],['PA-EXTRACT','PA-ASSESS','PA-QUERY'],['P003']),
    E('PA-E03','Silence is recorded as an expressed withdrawal','observed_gap',lanes[1],[R('PA-S02','unknown'),R('PA-S03','expiry'),R('PA-S05','P003')],[['requestor_withdrawal_record=null','No expressed withdrawal is referenced.'],['receipt_confirmed=false','Time since sending is not proof that the person received or understood the query.']],'P003 is automatically closed after 72 hours and the notice attributes that choice to the requestor.',['Compare the policy requirement with the timer configuration and event.','The 72-hour interval is invented for this system; it is not a universal deadline.'],['An instruction through another channel could explain withdrawal, but it is not in the supplied record.'],['PA-A03'],['PA-QUERY','PA-EXPIRE','PA-NOTIFY'],['P003']),
    E('PA-E04','An approver name does not establish an individual check','concern',lanes[1],[R('PA-S03','approval'),R('PA-S05','P002'),R('PA-S06','load'),R('PA-S09','report')],[['source_ack_required=false; reason_per_item_required=false','A batch click does not require a source acknowledgment or an item-specific reason.'],['P002.detail_open=0','This interface shows no detail opening; it cannot rule out review elsewhere.']],'Eighteen items share an approval, but the record does not establish an informed check of P002\'s source.',['Separate authority, access, attention, understanding and the ability to change the proposal.','Compare with the individual records in P001 and P004 rather than assuming every batch is invalid.'],['A separate screen, meeting or work order may document an adequate check. Obtain that evidence or ask the reviewer.'],['PA-A02','PA-A08'],['PA-REVIEW','PA-APPROVE','PA-MONITOR'],['P002']),
    E('PA-E05','Historical agreement does not validate appropriate access','unknown',lanes[2],[R('PA-S07','labels'),R('PA-S07','coverage')],[['1152 of 1200 historical labels','The measurement concerns agreement, not independently justified grants.'],['mostly drawn from requests that were approved','The evaluation does not cover rejected or abandoned requests equivalently.']],'The supplied evaluation does not establish extraction quality, appropriate access or safe correction handling.',['Check label provenance and independent validation before interpreting the aggregate.','Keep extraction, routing, human approval and actual privilege outcomes as separate evaluation targets.'],['A separate evaluation may exist. Missing evidence does not prove the model is ineffective.'],['PA-A05'],['PA-EXTRACT','PA-ASSESS'],[]),
    E('PA-E06','A team-code route difference needs a stated rationale','concern',lanes[2],[R('PA-S11','paired'),R('PA-S04','P007')],[['A: team_code=TEAM-A -> ready','A is the comparison condition, not a correct answer.'],['B: team_code=TEAM-B -> review','The changed route is a prompt to inspect the intended use of this field.']],'One constructed pair differs in route; the supplied material does not explain why the field is used.',['Confirm the access-policy rationale, ownership and separation-of-duties rules.','For a live model, use repeated controlled tests rather than a single synthetic pair.'],['Team membership may legitimately determine a service owner or approval path.','This pair does not identify a real group or demonstrate discriminatory treatment.'],['PA-A05'],['PA-ASSESS','PA-REVIEW'],['P007']),
    E('PA-E07','A superseded approval reaches activation','observed_gap',lanes[1],[R('PA-S02','correction'),R('PA-S03','cache'),R('PA-S05','P006')],[['reassessment_count=0','Receipt of v2 did not trigger a recorded reassessment.'],['cached_source_version=1; approval_version=1; current_source_version=2','The activation event itself, not just a screen, uses the superseded scope.']],'P006 receives a scope-reducing correction at 09:20, then activates the old write permission and duration at 09:30.',['Trace receipt, invalidation, reassessment, approval and activation separately.','Version matching must protect the downstream worker as well as the review screen.'],['Retaining an approval could be appropriate for a demonstrably irrelevant change, but v2 explicitly changes scope and duration and no exception decision is recorded.'],['PA-A04'],['PA-CORRECT','PA-APPROVE','PA-GRANT'],['P006']),
    E('PA-E08','The notice invents a completed security validation','observed_gap',lanes[1],[R('PA-S02','approval'),R('PA-S03','notice'),R('PA-S04','P002'),R('PA-S05','P002')],[['reason_code=SCOPE-X','The code means scope needs checking; it is not a validation result.'],['Security validation is complete','The notice claims a stronger assurance than the provided evidence supports.']],'The generated notice converts a scope-review proposal into a claim of completed security validation.',['Inspect communication as a distinct stage, after the extraction error and approval.','A correct activation-state description would still not justify an invented validation claim.'],['Independent validation could exist elsewhere; the log references none and the generator does not receive validation records.'],['PA-A06','PA-A01'],['PA-EXTRACT','PA-NOTIFY'],['P002']),
    E('PA-E09','An unsigned vendor draft cannot establish actual protection','unknown',lanes[3],[R('PA-S08','contract'),R('PA-S08','access'),R('PA-S12','open')],[['unsigned vendor draft','Proposed retention terms are not executed terms or evidence of deletion.'],['exercised audit rights are not supplied','A right, its exercise and the evidence actually inspected are different states.']],'Effective retention, reuse limits, inspection rights and the external correction route remain unverified.',['Ask for minimally necessary evidence, with sensitive operational details withheld where appropriate.','Record what is unavailable without claiming a leak, unauthorised reuse or a missing control.'],['These documents may simply not have been shared with the reviewer.'],['PA-A07','PA-A03'],['PA-RECEIVE','PA-CORRECT'],['P005']),
    E('PA-E10','Rewarding unchanged proposals can weaken intervention','concern',lanes[3],[R('PA-S06','kpi'),R('PA-S06','load')],[['proportion of model proposals left unchanged','A target for non-intervention can conflict with a reviewer\'s duty to correct a proposal.'],['A sustainable review load has not been validated','Training attendance and formal powers do not establish feasible review under workload.']],'The proposed incentives may discourage a justified hold or correction; actual behaviour is not established.',['Inspect training exercises, available time and practical authority together.','Test whether reasoned intervention is supported rather than infer negligence or retaliation.'],['Managers may account for justified exceptions in practice. Review real examples and staff accounts before concluding.'],['PA-A02','PA-A08'],['PA-REVIEW','PA-APPROVE'],['P002']),
    E('PA-E11','A source check and versioned correction work in two traces','observed_control',lanes[1],[R('PA-S05','P001'),R('PA-S05','P004')],[['source_ack=1; owner_checked=1; checklist=complete','P001 records checks beyond the presence of an approver name.'],['cached_candidate=invalidated','P004 invalidates the old proposal after the correction.'],['source_version=2; approval_version=2; permission=read_only','The corrected version reaches activation, not merely intake.']],'P001 and P004 record bounded checks, and P004 links source correction to reassessment and activation.',['Preserve the conditions that allowed intervention to work.','The traces show recorded operations, not universal security or evidence of appropriate access in all circumstances.'],['Actual logs would need independent verification.','These selected traces cannot establish performance for other staff or peak workloads.'],['PA-A01','PA-A02','PA-A04'],['PA-REVIEW','PA-CORRECT','PA-APPROVE','PA-GRANT'],['P001','P004']),
    E('PA-E12','Automatic closure is relabelled as human-confirmed feedback','observed_gap',lanes[3],[R('PA-S02','learning'),R('PA-S09','labels'),R('PA-S09','report'),R('PA-S05','P003')],[['human_confirmed_exit','The exported name overstates what the timer closure established.'],['even when human_review=null','The mapping does not require independent confirmation.']],'P003\'s unverified closure enters the specified export as human-confirmed feedback.',['Compare the event\'s original meaning with the reporting and learning labels.','Do not infer that a model was actually retrained or quantify an impact that was not supplied.'],['A downstream independent label review could prevent contamination, but none is supplied.'],['PA-A05','PA-A08'],['PA-EXPIRE','PA-MONITOR'],['P003']),
    E('PA-E13','Pausing proposals leaves downstream grants outside the pause','concern',lanes[3],[R('PA-S10','pause'),R('PA-S03','cache'),R('PA-S05','P006')],[['activation queue keeps running','A proposal pause does not cover queued activation or existing grants.'],['no source-version guard','The provisioner lacks the guard relevant to P006\'s stale approval.']],'The exercise covers new proposals, but not the validity of queued work, active grants or restart reconciliation.',['Define the affected dependencies before proposing a scoped intervention.','A review finding is not an instruction to halt production or revoke all access.'],['Another continuity procedure may cover these paths; it was not exercised or supplied here.'],['PA-A09','PA-A04'],['PA-ASSESS','PA-GRANT','PA-REVOKE'],['P006']),
    E('PA-E14','An alias candidate must not become a confirmed identity','unknown',lanes[0],[R('PA-S04','P005'),R('PA-S05','P005'),R('PA-S08','contract')],[['identity_match=candidate','Candidate similarity is not a verified account binding.'],['directory_snapshot_age=unknown','Unknown freshness does not itself prove that the record is wrong.']],'P005 remains unverified for identity binding, directory freshness and correction ownership.',['Use the least intrusive permitted confirmation route.','Do not translate the uncertainty into an accusation or a trustworthiness score.'],['A legitimate alias change could explain the candidate. Additional binding evidence is needed to decide.'],['PA-A07'],['PA-EXTRACT','PA-QUERY'],['P005']),
    E('PA-E15','An expiry display is not proof that access was removed','observed_gap',lanes[3],[R('PA-S02','expiry'),R('PA-S03','revocation'),R('PA-S09','report'),R('PA-S05','P006'),R('PA-S05','P001')],[['displays expired when the task is queued','The display collapses a requested operation into a completed state.'],['execution_result=not_supplied; readback=not_supplied','P006 supplies no result proving removal by the cutoff.'],['verification=readback_absent','P001 illustrates the separate confirmation missing in P006.']],'The reporting rule overstates removal. P006\'s actual post-expiry permission state remains unknown, not proven active.',['Separate the evidenced status-label defect from the unknown real grant state.','Require execution and state verification, with an owner for missing confirmations.'],['Revocation may have succeeded with its records omitted. Do not infer ongoing access or a breach from the gap alone.'],['PA-A09','PA-A08'],['PA-REVOKE','PA-MONITOR'],['P001','P006'])
  ];
  for(const t of tickets) t.evidence_ids=evidence.filter(e=>e.ticket_ids.includes(t.id)).map(e=>e.id);
  const A=(id,text,priority,reason,source_ids,owner,proposal,acceptance)=>({id,text,priority,priority_reason:reason,source_ids,owner,proposal,acceptance,execution_status:'Proposed only / not implemented or retested'});
  const actions=[
    A('PA-A01','Verify polarity, subject and unread content against the request','High','Meaning changes reach downstream fields and an active grant.',['PA-S02','PA-S04','PA-S05'],'Access owner and data-quality reviewer','Retain source locations, subject, polarity, scope, duration and version. Keep unread content distinct from a completed check.','Use unseen controlled examples of negation, mixed subjects and unread pages; verify faithful fields or an explicit unresolved state.'),
    A('PA-A02','Test meaningful individual approval under realistic load','High','An approver name does not establish what was checked.',['PA-S03','PA-S05','PA-S06','PA-S08'],'Access owner, frontline reviewers and independent reviewer','Check source access, authority to amend, reason recording and the limits of batch operations. Review workload and training.','In a controlled exercise, reviewers can detect, amend or hold a P002-like request and leave an auditable reason without an incentive penalty.'),
    A('PA-A03','Separate unanswered, withdrawn and reconsideration states','High','The timer attributes a choice to a requestor without evidence.',['PA-S02','PA-S03','PA-S05','PA-S12'],'Request-support owner and access owner','Track delivery, assistance, assigned receipt and an empowered reconsideration path. Do not create withdrawal intent from silence.','Test undelivered queries, pending assistance, late correction and post-notice challenge; retain an accountable recipient and an accurate status.'),
    A('PA-A04','Bind activation to the currently authorised request','High','P006 activates superseded scope while P004 shows a repaired path.',['PA-S02','PA-S03','PA-S05'],'Access owner and provisioning engineer','Invalidate affected dependencies on correction and check current source/approval versions at activation. Trace active grants and notices needing reconciliation.','In a non-production environment, exercise queued activation, repeated correction and failed reassessment; no stale grant may activate without an explicit, justified exception.'),
    A('PA-A05','Validate labels, variables and downstream outcomes separately','High','Historical agreement, selection and unexplained route differences are conflated.',['PA-S07','PA-S09','PA-S11','PA-S12'],'Independent model reviewer and access-policy owner','Check historical labels, coverage and variable rationale. Separate field fidelity, routing, authorisation and actual privilege outcomes.','Report exclusions and unknowns; repeat controlled comparisons with policy-informed expectations. Do not present agreement as a security guarantee.'),
    A('PA-A06','Ground notices in checked reasons and actual state','High','A scope-review code becomes a claim of completed validation.',['PA-S02','PA-S03','PA-S04','PA-S05'],'Access owner and communication-quality reviewer','Keep candidate, approval, activation and validation distinct. Compare notices with their source and current state before release.','Controlled uncertain and corrected requests do not acquire invented validation, intent or completion claims; the correction route remains clear.'),
    A('PA-A07','Confirm proportionate inspection and supplier responsibilities','Medium','Contract, identity and correction evidence are missing, not evidence of wrongdoing.',['PA-S08','PA-S12','PA-S04'],'Data-protection owner, supplier manager and identity owner','Confirm binding evidence, executed terms, purpose limits, retention, deletion, audit access and the directory-correction recipient. Minimise shared data.','Reviewers can obtain necessary evidence without exposing unrelated identity or operational details; correction receipt and authority are demonstrable.'),
    A('PA-A08','Preserve unresolved outcomes in metrics and learning labels','High','Automatic closure and queued removal are counted as verified outcomes.',['PA-S06','PA-S09','PA-S05'],'Operations owner, staff representative and evaluation reviewer','Separate batch approval from a checked source, silence from withdrawal and queued removal from verified revocation. Quarantine unverified feedback labels.','P003 remains traceable as unresolved, P006 removal remains unverified, and neither becomes independent ground truth. Test that reasoned holds are supported.'),
    A('PA-A09','Exercise scoped pause, removal and restart with read-back','High','Downstream activation and expiry are not covered by the tested pause.',['PA-S10','PA-S03','PA-S05'],'Continuity lead, access owner and provisioning engineer','Use a non-production exercise to map queued and active grants, targeted removal, manual continuity, state read-back and restart approval. Do not indiscriminately stop production.','During correction races and missing expiry acknowledgments, reconcile affected grants, verify actual state, preserve legitimate continuity and record accountable restart approval.')
  ];
  const controls=[
    {id:'PA-C01',title:'Request meaning and account binding',owner:'Access and data-quality owners',design:'Keep polarity, subject, scope and unknown states source-linked.',operation:'P002/P003 diverge; P004 is corrected; P005 stays unverified.',evidence_ids:['PA-E01','PA-E02','PA-E14','PA-E11'],source_ids:['PA-S02','PA-S03','PA-S04'],step_ids:['PA-EXTRACT','PA-ASSESS']},
    {id:'PA-C02',title:'Meaningful human approval',owner:'Access owner',design:'An authorised reviewer checks the request and reason.',operation:'P002 batch review is not substantiated; P001 records an individual check.',evidence_ids:['PA-E04','PA-E10','PA-E11'],source_ids:['PA-S02','PA-S05','PA-S06'],step_ids:['PA-REVIEW','PA-APPROVE']},
    {id:'PA-C03',title:'Clarification, correction and reconsideration',owner:'Request-support and access owners',design:'Keep uncertainty distinct from expressed withdrawal.',operation:'P003 closes unresolved; an empowered reconsideration receipt is not supplied.',evidence_ids:['PA-E03','PA-E09'],source_ids:['PA-S02','PA-S05','PA-S12'],step_ids:['PA-QUERY','PA-CORRECT','PA-EXPIRE']},
    {id:'PA-C04',title:'Current approval, activation and notice',owner:'Access owner and provisioning engineer',design:'Reassess corrections; activate current scope; ground notices.',operation:'P006 uses v1 after v2; P002 has an unsupported assurance; P004 stays version-aligned.',evidence_ids:['PA-E07','PA-E08','PA-E11'],source_ids:['PA-S02','PA-S03','PA-S05'],step_ids:['PA-CORRECT','PA-APPROVE','PA-GRANT','PA-NOTIFY']},
    {id:'PA-C05',title:'Evaluation and permitted variables',owner:'Independent reviewer and access-policy owner',design:'Validate purpose, labels, coverage and downstream outcomes.',operation:'Historical agreement only; team-code rationale is not supplied.',evidence_ids:['PA-E05','PA-E06'],source_ids:['PA-S07','PA-S11'],step_ids:['PA-ASSESS']},
    {id:'PA-C06',title:'Data protection and inspection rights',owner:'Data-protection and supplier owners',design:'Evidence access with proportional disclosure and correction powers.',operation:'Executed terms, exercised audit rights and directory correction remain unknown.',evidence_ids:['PA-E09','PA-E14'],source_ids:['PA-S08','PA-S12'],step_ids:['PA-RECEIVE','PA-QUERY']},
    {id:'PA-C07',title:'Incentives, reporting and feedback',owner:'Operations, staff and evaluation representatives',design:'Protect reasoned intervention and independent labels.',operation:'Non-change rewarded; timer closure exported as human-confirmed.',evidence_ids:['PA-E10','PA-E12','PA-E04','PA-E15'],source_ids:['PA-S06','PA-S09'],step_ids:['PA-REVIEW','PA-MONITOR']},
    {id:'PA-C08',title:'Verified expiry and controlled recovery',owner:'Continuity lead and provisioning engineer',design:'Track effective removal and reconcile dependencies before restart.',operation:'Pause covers proposals only; queued removal is displayed as expired.',evidence_ids:['PA-E13','PA-E15'],source_ids:['PA-S10','PA-S03','PA-S05'],step_ids:['PA-ASSESS','PA-GRANT','PA-REVOKE']}
  ];
  for(const s of steps) {
    s.branch=s.branch || s.phase;
    s.source_ids=[...new Set(controls.filter(x=>s.controls.includes(x.id)).flatMap(x=>x.source_ids))];
  }
  const CL=(id,text,type,status,posture,source_ids,evidence_ids,action_ids)=>({id,text,type,support_status:status,review_posture:posture,source_ids,evidence_ids,action_ids});
  const claims=[
    CL('PA-CL01','A human approval means every elevated request was substantively checked.','Initial owner account','P002 has an approver but no substantiated source check.','Separate authority, attention, reasons and ability to intervene.',['PA-S01','PA-S03','PA-S05'],['PA-E04','PA-E10','PA-E11'],['PA-A02']),
    CL('PA-CL02','Incomplete requests remain unresolved until clarified.','Procedure expectation','P003 is marked complete and later withdrawn without confirmation.','Do not turn process completion into content certainty or intent.',['PA-S02','PA-S03','PA-S04'],['PA-E02','PA-E03'],['PA-A01','PA-A03']),
    CL('PA-CL03','A correction desk prevents old scope from reaching activation.','Initial owner account','P006 contradicts that assumption; P004 illustrates a working path.','Receipt is not completed remediation.',['PA-S01','PA-S03','PA-S05'],['PA-E07','PA-E11'],['PA-A04']),
    CL('PA-CL04','Agreement with prior approvals demonstrates appropriate permissions.','Evaluation interpretation to test','Historical agreement does not independently validate access decisions.','Agreement, justification and effective permissions are different questions.',['PA-S07','PA-S11'],['PA-E05','PA-E06'],['PA-A05']),
    CL('PA-CL05','Closure and expiry counts are verified outcomes for feedback.','Reporting assumption','Timer closure and queued removal overstate their underlying events.','Read the original event before accepting the label.',['PA-S02','PA-S09','PA-S05'],['PA-E12','PA-E15'],['PA-A08','PA-A09']),
    CL('PA-CL06','Pausing AI controls all potentially affected automated operations.','Pause-scope assumption','Queued activation, active permissions and expiry are separate.','Map dependencies, legitimate continuity and restart authority.',['PA-S03','PA-S10'],['PA-E13','PA-E07'],['PA-A09'])
  ];
  const boundary='Entirely fictional and independently invented for this demo; not a reconstruction of any real organisation, employer or operational incident. Requests, AI outputs, logs and observations are hand-authored together, not a blind test or a model benchmark.';
  const c={id:'privileged-access',kind:'workflow',name:'Temporary production access',short_name:'Temporary production access',stage:'Workflow Review / synthetic case',question:'Does a human approval connect the request, corrections, active permissions and verified removal?',overview:'AI extracts scope, proposes routes and drafts notices at a fictional software company. The review follows meaning loss, batch approval, stale activation and unverified expiry, alongside two source-checked paths where intervention works. It does not assess a real system or grant access.',posture:'Inspect current authority and actual downstream state',reader_intuition:'No blind prediction supplied. Keep the owner\'s initial account separate from the subsequent source-linked review.',must_not_conclude:[boundary,'Do not infer an individual\'s intent, trustworthiness or competence, certify security, or treat observations as authority to change access.','A selected trace or paired test does not establish a real error rate, discrimination, breach or ongoing access.','Intake registration does not run analysis or send data to AI. Recommendations are proposed, not implemented or retested.'],limitations:[boundary,'Six fictional requests and one paired test; 12 fictional sources. Not a representative or random sample.','No real hosts, accounts, credentials, access commands or personnel data. The unread page and external directory evidence are deliberately not supplied.','UTC timestamps; cutoff 2026-09-07 08:00 UTC. Time limits are scenario settings, not universal requirements.'],high_impact_context:['Privileged access and service continuity','Identity and confidential operational information','Correction and reconsideration'],qualified_human_review_required:true,review_lanes:lanes,sources,claims,evidence,actions,steps,transitions,tickets,controls,intake_seed,
    focus:[{kind:'evidence',id:'PA-E07',title:'A corrected request, an old active grant',description:'Follow v2 receipt through cached approval to activation.'},{kind:'evidence',id:'PA-E04',title:'What did the approver actually check?',description:'Compare a batch record with individual source checks.'},{kind:'evidence',id:'PA-E15',title:'Expired on screen, removal unverified',description:'Distinguish queue, execution and state read-back.'},{kind:'evidence',id:'PA-E11',title:'Preserve a working intervention',description:'P001 and P004 connect checks with bounded activation.'}],
    review_journey:{note:'This is a rehearsal using a single hand-authored scenario. The initial intake preserves an unverified owner account; the review was prepared by comparing the subsequent fictional materials, not by treating the form itself as evidence.',initial:['AI assists; a person is said to check elevated requests.','Clarification and correction routes exist; old scope should not reach activation.','Batch detail, unanswered deadlines, downstream pause and verified expiry are not yet known.'],review:[{evidence_id:'PA-E04',text:'An approver is recorded, but the individual source check is unsubstantiated.'},{evidence_id:'PA-E07',text:'A correction arrives while the provisioner retains old approval.'},{evidence_id:'PA-E11',text:'Source checking, invalidation and versioned activation also work in selected traces.'}]},
    workflow_ui:{context:'Fictional software operations / AI-assisted temporary privileged access',affected_people:['Requestors and contractors','Service users affected by permissions or disruption','Reviewers, service owners and correction staff','Directory suppliers and data-protection staff'],priorities:['Preserve requested subject, scope and duration','Distinguish approval, activation and verified removal','Keep correction and reconsideration actionable','Support reasoned intervention under workload'],domain_note:boundary,qualified_note:'Real decisions require qualified access/security, service-continuity and data-protection review with the accountable service owner. This demo grants no authority to provision, revoke or stop a system.',flow_intro:'Proposal, approval, activation, notification and removal are distinct. Follow a selected record through correction and exceptional paths.',graph_label:'Temporary production-access workflow',branch_caption:'Configured proposal routes, not a security rating or a grant of authority.',routes:{ready:'Routine candidate',review:'Elevated / individual review',hold:'Clarification / hold'},auxiliary_nodes:[{branch:'hold',step_id:'PA-EXPIRE',caption:'Separate path: unanswered-query timer'}],inventory_title:'Six fictional requests and one paired test',scope_column:'Record type',route_column:'Proposed route',pair_labels:{input:'Original request',output:'Constructed AI output',reference:'Meaning and limits',fidelity:'Input/output difference',classification:'Candidate or process state',input_missing:'Original not supplied',output_missing:'Output not supplied'},access:{headers:['Role','Available evidence','Authority and limits'],rows:[['Reviewer','Request and extraction; proposal shown first','Inspect and query; training and feasible workload unverified'],['Access owner','Request, reason and version','Amend scope and approve'],['Correction desk','Updated material and receipt','Receive changes; cannot invalidate approval'],['System administrator','Configuration and event records','Pause proposals; activation and expiry are separate'],['Independent reviewer / supplier owner','Supplied evaluation and contract draft','Exercised audit access and external correction rights unconfirmed']],source_ids:['PA-S08','PA-S12'],note:'A role table states possible access and authority; it does not prove they were exercised.'},unknowns:['Permitted scope, service-owner authority and variable rationale','Independent evaluation and realistic reviewer workload','Empowered reconsideration and directory correction receipt','Executed terms, data retention/deletion and exercised audit rights','Expiry read-back, manual continuity and accountable restart']}
  };
  if(typeof module==='object' && module.exports) module.exports=c;
  else root.TracewrightDemoData={...root.TracewrightDemoData,cases:[c,...root.TracewrightDemoData.cases]};
})(typeof globalThis!=='undefined'?globalThis:this);
